sonar.projectKey=Arielben75_practica_devopssec
sonar.organization=arielben75

# This is the name and version that are displayed in the SonarCloud UI.
sonar.projectName=practica_devopssec
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=.

# Encoding of the source code. Default is default system encoding.
sonar.sourceEncoding=UTF-8

# Exclude some files/folders from analysis
sonar.exclusions=node_modules/**, dist/**, **/__tests__/**, .github/**
